title: Boubou Thiam Niang
description: Updated on October 10, 2023
baseurl:""
plugins:
  - jekyll-remote-theme
remote_theme: ngzhio/jekyll-theme-hamilton
author: Boubou Thiam Niang
avatar: profil_resized.jpg
email: 	boubouniang@yahoo.fr
location: France
skin: midnight
lang: en

