title: Boubou Thiam Niang
description: Bookmark this to keep an eye on my project updates!
plugins:
  - jekyll-remote-theme
remote_theme: madeslowly/slow-science
author: Boubou Thiam Niang
avatar: 	string 	The avatar of the author of the site.
email: 	boubouniang@yahoo.fr
location: France
skin: midnight
lang: en
logo: /profil_resized.jpg
