title: Boubou Thiam Niang
description: Updated on October 10, 2023
plugins:
  - jekyll-remote-theme
remote_theme: minimal-mistakes-jekyll
author: Boubou Thiam Niang
avatar: profil_resized.jpg
email: 	boubouniang@yahoo.fr
location: France
skin: midnight
lang: en

